'use client';
import { ChangeEvent, DragEvent, PointerEvent, WheelEvent, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { DeveloperPanel } from '@/components/developer-panel';
import { AiPanel } from '@/components/ai-panel';
import { ExportPanel } from '@/components/export-panel';
import { drawMaskOverlay, renderImage } from '@/lib/editor/render';
import { parseProject, serializeProject } from '@/lib/editor/persistence';
import { CONTROL_DEFINITIONS } from '@/lib/editor/tools';
import { ADJUSTMENT_KEYS, Adjustments, EditCommand, EditPlan, EditorDocument, INITIAL_ADJUSTMENTS, MaskDefinition, MaskType, NormalizedPoint, createId } from '@/lib/editor/types';
import { useEditor } from '@/lib/editor/use-editor';

const presets=[{name:'Tự nhiên',values:{contrast:8,vibrance:12,shadows:8}},{name:'Điện ảnh',values:{contrast:22,saturation:-12,temperature:-8,vignette:24}},{name:'Ấm áp',values:{temperature:24,tint:5,vibrance:16}},{name:'Đen trắng',values:{saturation:-100,contrast:18,clarity:12}}] satisfies {name:string;values:Partial<Adjustments>}[];
function editCommand(key:keyof Adjustments,value:number,targetId:string|null,origin:EditCommand['origin']='user'):EditCommand{return{id:createId('cmd'),version:1,tool:`adjust.${key}`,target:targetId?{type:'mask',id:targetId}:{type:'document'},parameters:{value},origin};}
function maskCommand(tool:string,id:string|null,parameters:EditCommand['parameters']={}):EditCommand{return{id:createId('cmd'),version:1,tool,target:id?{type:'mask',id}:{type:'document'},parameters,origin:'user'};}
function download(blob:Blob,name:string){const url=URL.createObjectURL(blob),link=window.document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),500);}

export default function Home(){
  const editor=useEditor();const canvasRef=useRef<HTMLCanvasElement>(null),overlayRef=useRef<HTMLCanvasElement>(null),imageInput=useRef<HTMLInputElement>(null),projectInput=useRef<HTMLInputElement>(null),imageRef=useRef<HTMLImageElement|null>(null),objectUrl=useRef<string|undefined>(undefined);
  const [image,setImage]=useState<HTMLImageElement|null>(null),[draft,setDraft]=useState<Adjustments|null>(null),[previewDoc,setPreviewDoc]=useState<EditorDocument|null>(null),[compare,setCompare]=useState(false),[dragging,setDragging]=useState(false),[devOpen,setDevOpen]=useState(false),[aiOpen,setAiOpen]=useState(false),[exportOpen,setExportOpen]=useState(false),[notice,setNotice]=useState('');
  const [selectedMaskId,setSelectedMaskId]=useState<string|null>(null),[workingMask,setWorkingMask]=useState<MaskDefinition|null>(null),[showOverlay,setShowOverlay]=useState(true),[drawing,setDrawing]=useState(false);
  const [viewport,setViewport]=useState({zoom:1,x:0,y:0}),[navigationMode,setNavigationMode]=useState<'zoom'|'pan'|null>(null);const spaceHeld=useRef(false),navigation=useRef<{mode:'zoom'|'pan';startX:number;startY:number;zoom:number;x:number;y:number;anchorX:number;anchorY:number}|null>(null);
  const baseDocument=previewDoc||editor.document;const selectedMask=baseDocument.masks.find(mask=>mask.id===selectedMaskId)||null;const activeAdjustments=selectedMask?.adjustments||baseDocument.adjustments;
  const displayDocument=useMemo(()=>{if(compare)return{...baseDocument,adjustments:{...INITIAL_ADJUSTMENTS},masks:[]};if(!draft)return baseDocument;return selectedMaskId?{...baseDocument,masks:baseDocument.masks.map(mask=>mask.id===selectedMaskId?{...mask,adjustments:draft}:mask)}:{...baseDocument,adjustments:draft};},[baseDocument,compare,draft,selectedMaskId]);

  const loadBlob=useCallback((blob:Blob,name:string,persist=true)=>{if(objectUrl.current)URL.revokeObjectURL(objectUrl.current);const url=URL.createObjectURL(blob);objectUrl.current=url;const next=new Image();next.onload=()=>{imageRef.current=next;setImage(next);if(persist){editor.setImage(blob,name);setAiOpen(true);setPreviewDoc(null);setDraft(null);}};next.src=url;},[editor]);
  useEffect(()=>{if(!editor.ready||image)return;const stored=editor.getStoredImage();if(stored.blob)loadBlob(stored.blob,stored.name||editor.document.name,false);},[editor.ready,image,editor,loadBlob]);
  useEffect(()=>{const frame=requestAnimationFrame(()=>{const canvas=canvasRef.current,source=imageRef.current;if(canvas&&source)renderImage(canvas,source,displayDocument,1200);});return()=>cancelAnimationFrame(frame);},[image,displayDocument]);
  useEffect(()=>{const frame=requestAnimationFrame(()=>{const canvas=canvasRef.current,overlay=overlayRef.current;if(canvas&&overlay)drawMaskOverlay(overlay,showOverlay&&!compare?(workingMask||selectedMask):null,canvas.width,canvas.height);});return()=>cancelAnimationFrame(frame);},[image,selectedMask,workingMask,showOverlay,compare,displayDocument]);
  useEffect(()=>{const down=(event:KeyboardEvent)=>{if(event.target instanceof HTMLElement && (event.target.matches('input,textarea,select')||event.target.isContentEditable))return;if(event.code==='Space'){spaceHeld.current=true;if(!(event.target instanceof HTMLInputElement))event.preventDefault();}if((event.metaKey||event.ctrlKey)&&event.key==='0'){event.preventDefault();resetViewport();}if((event.metaKey||event.ctrlKey)&&event.key==='1'){event.preventDefault();setViewport(current=>({...current,zoom:1,x:0,y:0}));}if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='z'){event.preventDefault();if(event.shiftKey)editor.redo();else editor.undo();setDraft(null);setWorkingMask(null);}};const up=(event:KeyboardEvent)=>{if(event.code==='Space')spaceHeld.current=false;};const blur=()=>{spaceHeld.current=false;navigation.current=null;setNavigationMode(null);};window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);};},[editor]);

  async function commit(key:keyof Adjustments,value:number){try{await editor.dispatch([editCommand(key,value,selectedMaskId)],`Điều chỉnh ${CONTROL_DEFINITIONS[key].label}${selectedMask?' · '+selectedMask.name:''}`);setDraft(null);setPreviewDoc(null);}catch(error){setNotice(error instanceof Error?error.message:'Không thể áp dụng');}}
  async function applyPreset(preset:(typeof presets)[number]){await editor.dispatch(Object.entries({...INITIAL_ADJUSTMENTS,...preset.values}).map(([key,value])=>editCommand(key as keyof Adjustments,value,selectedMaskId,'preset')),`Preset ${preset.name}${selectedMask?' · '+selectedMask.name:''}`);setDraft(null);}
  async function addMask(type:MaskType){const id=createId('mask');await editor.dispatch([maskCommand('mask.create',null,{id,type,name:type==='brush'?'Cọ vùng chọn':type==='radial'?'Vùng elip':'Dải chuyển sắc'})],`Tạo mask ${type}`);setSelectedMaskId(id);setShowOverlay(true);setDraft(null);}
  async function updateMask(parameters:EditCommand['parameters'],label='Cập nhật vùng chọn'){if(!selectedMaskId)return;await editor.dispatch([maskCommand('mask.update',selectedMaskId,parameters)],label);setWorkingMask(null);}
  async function deleteMask(){if(!selectedMaskId)return;await editor.dispatch([maskCommand('mask.delete',selectedMaskId)],'Xóa vùng chọn');setSelectedMaskId(null);setDraft(null);}
  function point(event:PointerEvent<HTMLCanvasElement>):NormalizedPoint{const rect=event.currentTarget.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(event.clientX-rect.left)/rect.width)),y:Math.max(0,Math.min(1,(event.clientY-rect.top)/rect.height))};}
  function startBrush(event:PointerEvent<HTMLCanvasElement>){if(event.metaKey||event.ctrlKey||spaceHeld.current||event.button===1||!selectedMask||selectedMask.type!=='brush')return;event.currentTarget.setPointerCapture(event.pointerId);setDrawing(true);const next={...selectedMask,geometry:{...selectedMask.geometry,strokes:[...(selectedMask.geometry.strokes||[]),[point(event)]]}};setWorkingMask(next);}
  function moveBrush(event:PointerEvent<HTMLCanvasElement>){if(!drawing||!workingMask)return;const strokes=[...(workingMask.geometry.strokes||[])],last=[...(strokes.at(-1)||[]),point(event)];strokes[strokes.length-1]=last;setWorkingMask({...workingMask,geometry:{...workingMask.geometry,strokes}});}
  async function finishBrush(){if(!drawing||!workingMask)return;setDrawing(false);await updateMask({geometry:workingMask.geometry},'Vẽ cọ vùng chọn');}
  function selectImage(file?:File){setAiOpen(false);if(file?.type.startsWith('image/')){loadBlob(file,file.name);setSelectedMaskId(null);resetViewport();}}
  function exportProject(){download(new Blob([serializeProject(editor.document,editor.transactions,editor.historyIndex)],{type:'application/json'}),`${editor.document.name.replace(/\.[^.]+$/,'')}.openphoto.json`);}
  async function importProject(file?:File){if(!file)return;try{editor.restore(parseProject(await file.text()));setSelectedMaskId(null);setNotice('Đã nạp project. Chọn lại ảnh nguồn nếu cần.');}catch(error){setNotice(error instanceof Error?error.message:'Không thể mở project');}}
  async function previewPlan(plan:EditPlan){const result=(await editor.preview(plan.commands)).document;setPreviewDoc(result);return result;}
  async function applyPlan(plan:EditPlan){await editor.dispatch(plan.commands,plan.title);setPreviewDoc(null);}
  async function applySingle(value:EditCommand){await editor.dispatch([value],`AI · ${value.tool}`);setPreviewDoc(null);}
  function beginNavigation(event:PointerEvent<HTMLElement>){const zoomShortcut=spaceHeld.current&&(event.metaKey||event.ctrlKey),mode=zoomShortcut?'zoom':spaceHeld.current||event.button===1?'pan':null;if(!mode)return;event.preventDefault();event.currentTarget.setPointerCapture(event.pointerId);const rect=event.currentTarget.getBoundingClientRect();navigation.current={mode,startX:event.clientX,startY:event.clientY,...viewport,anchorX:event.clientX-rect.left-rect.width/2,anchorY:event.clientY-rect.top-rect.height/2};setNavigationMode(mode);}
  function moveNavigation(event:PointerEvent<HTMLElement>){const active=navigation.current;if(!active)return;event.preventDefault();if(active.mode==='pan'){setViewport({zoom:active.zoom,x:active.x+event.clientX-active.startX,y:active.y+event.clientY-active.startY});return;}const zoom=Math.max(.1,Math.min(8,active.zoom*Math.exp((event.clientX-active.startX)*.008))),ratio=zoom/active.zoom;setViewport({zoom,x:active.anchorX-(active.anchorX-active.x)*ratio,y:active.anchorY-(active.anchorY-active.y)*ratio});}
  function endNavigation(){navigation.current=null;setNavigationMode(null);}
  function wheelNavigation(event:WheelEvent<HTMLElement>){if(!event.metaKey&&!event.ctrlKey)return;event.preventDefault();const rect=event.currentTarget.getBoundingClientRect(),px=event.clientX-rect.left-rect.width/2,py=event.clientY-rect.top-rect.height/2;setViewport(current=>{const zoom=Math.max(.1,Math.min(8,current.zoom*Math.exp(-event.deltaY*.002)));const ratio=zoom/current.zoom;return{zoom,x:px-(px-current.x)*ratio,y:py-(py-current.y)*ratio};});}
  function resetViewport(){setViewport({zoom:1,x:0,y:0});}
  function stepZoom(direction:1|-1){
    setViewport(current=>{
      const zoom=Math.max(.1,Math.min(8,current.zoom*(direction===1?1.25:1/1.25)));
      const ratio=zoom/current.zoom;
      return{zoom,x:current.x*ratio,y:current.y*ratio};
    });
  }
  function drop(event:DragEvent){event.preventDefault();setDragging(false);selectImage(event.dataTransfer.files[0]);}
  const valueFor=(key:keyof Adjustments)=>draft?.[key]??activeAdjustments[key];

  return <main className="flex h-dvh min-h-[650px] flex-col overflow-hidden bg-[#111214] text-[#eee]">
    <header className="flex h-14 shrink-0 items-center justify-between border-b border-white/10 bg-[#17181b] px-4"><div className="flex items-center gap-3"><div className="grid h-8 w-8 place-items-center rounded-lg bg-[#e7ff46] font-black text-black">O</div><div><div className="text-sm font-semibold">OpenPhoto</div><div className="max-w-48 truncate text-[9px] text-white/40">{editor.document.name} · schema v{editor.document.schemaVersion}</div></div></div><div className="flex items-center gap-1 rounded-lg bg-black/20 p-1"><button onClick={()=>{editor.undo();setDraft(null);setWorkingMask(null)}} disabled={editor.historyIndex<0} className="toolbar-button">↶</button><button onClick={()=>{editor.redo();setDraft(null);setWorkingMask(null)}} disabled={editor.historyIndex>=editor.transactions.length-1} className="toolbar-button">↷</button><span className="mx-1 h-5 w-px bg-white/10"/><span className="px-2 text-[9px] text-white/35">{editor.historyIndex+1}/{editor.transactions.length} thao tác</span></div><div className="flex gap-2"><button onClick={exportProject} className="top-button">Lưu project</button><button onClick={()=>projectInput.current?.click()} className="top-button">Mở project</button><button onClick={()=>imageInput.current?.click()} className="top-button">Mở ảnh</button><button disabled={!image} onClick={()=>setExportOpen(true)} className="rounded-lg bg-[#e7ff46] px-4 py-2 text-[10px] font-bold text-black disabled:opacity-30">Xuất ảnh</button></div></header>
    <div className="grid min-h-0 flex-1 grid-cols-[210px_minmax(0,1fr)_320px]">
      <aside className="min-h-0 overflow-y-auto border-r border-white/10 bg-[#17181b] p-3"><div className="mb-3 flex items-center justify-between"><h2 className="text-[10px] font-semibold uppercase tracking-wider text-white/60">Vùng chỉnh sửa</h2><div className="flex gap-2"><button disabled={!image} onClick={()=>setAiOpen(true)} className="text-[#e7ff46] disabled:opacity-25" title="AI chỉnh ảnh">✦ AI</button><button onClick={()=>setDevOpen(true)} className="text-[9px] text-white/30" title="Developer Tool Lab">{'{ }'}</button></div></div><button onClick={()=>{setSelectedMaskId(null);setDraft(null)}} className={`mask-list-item ${!selectedMaskId?'mask-list-active':''}`}><span>◐</span><span>Toàn bộ ảnh</span></button><div className="my-2 h-px bg-white/8"/>{editor.document.masks.map(mask=><button key={mask.id} onClick={()=>{setSelectedMaskId(mask.id);setDraft(null);setShowOverlay(true)}} className={`mask-list-item ${selectedMaskId===mask.id?'mask-list-active':''}`}><span>{mask.type==='brush'?'✎':mask.type==='radial'?'◉':mask.type==='semantic'?'✦':'▱'}</span><span className="truncate">{mask.name}</span><span className={`ml-auto h-1.5 w-1.5 rounded-full ${mask.enabled?'bg-[#e7ff46]':'bg-white/20'}`}/></button>)}<div className="mt-3 grid grid-cols-3 gap-1"><button onClick={()=>addMask('brush')} className="mask-add">Cọ</button><button onClick={()=>addMask('radial')} className="mask-add">Elip</button><button onClick={()=>addMask('linear')} className="mask-add">Dải</button></div>
        {selectedMask&&<div className="mt-5 border-t border-white/10 pt-4"><div className="mb-3 flex justify-between"><span className="text-[10px] font-semibold">{selectedMask.name}</span><button onClick={deleteMask} className="text-[9px] text-red-300/60 hover:text-red-300">Xóa</button></div><label className="mask-setting"><span>Hiện overlay</span><input type="checkbox" checked={showOverlay} onChange={e=>setShowOverlay(e.target.checked)}/></label><label className="mask-setting"><span>Đảo vùng</span><input type="checkbox" checked={selectedMask.inverted} onChange={e=>updateMask({inverted:e.target.checked},'Đảo vùng chọn')}/></label><label className="mask-setting"><span>Bật mask</span><input type="checkbox" checked={selectedMask.enabled} onChange={e=>updateMask({enabled:e.target.checked},'Bật/tắt vùng chọn')}/></label><label className="mt-3 block text-[9px] text-white/40">Feather · {Math.round(selectedMask.feather*100)}</label><input className="adjustment-range mt-2" type="range" min="0" max="1" step=".01" value={selectedMask.feather} onChange={e=>setWorkingMask({...selectedMask,feather:Number(e.target.value)})} onPointerUp={()=>workingMask&&updateMask({feather:workingMask.feather},'Feather vùng chọn')}/>{selectedMask.type==='brush'&&<><label className="mt-4 block text-[9px] text-white/40">Kích thước cọ · {Math.round((workingMask?.geometry.brushSize||selectedMask.geometry.brushSize||.08)*100)}</label><input className="adjustment-range mt-2" type="range" min=".01" max=".35" step=".01" value={workingMask?.geometry.brushSize||selectedMask.geometry.brushSize||.08} onChange={e=>setWorkingMask({...selectedMask,geometry:{...selectedMask.geometry,brushSize:Number(e.target.value)}})} onPointerUp={()=>workingMask&&updateMask({geometry:workingMask.geometry},'Đổi kích thước cọ')}/><button onClick={()=>updateMask({geometry:{...selectedMask.geometry,strokes:[]}},'Xóa nét cọ')} className="mt-3 w-full rounded-lg border border-white/10 py-2 text-[9px] text-white/45">Xóa nét cọ</button></>}</div>}
      </aside>
      <section onPointerDown={beginNavigation} onPointerMove={moveNavigation} onPointerUp={endNavigation} onPointerCancel={endNavigation} onWheel={wheelNavigation} onDoubleClick={resetViewport} onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={drop} className={`relative grid min-h-0 place-items-center overflow-hidden p-8 ${dragging?'bg-[#e7ff46]/5':'bg-[#0d0e10]'} ${navigationMode==='pan'?'cursor-grabbing':navigationMode==='zoom'?'cursor-zoom-in':''}`}><div className="absolute inset-0 editor-grid opacity-30"/>{image?<div className="relative h-full w-full min-h-0 min-w-0 will-change-transform" style={{transform:`translate(${viewport.x}px, ${viewport.y}px) scale(${viewport.zoom})`}}><canvas ref={canvasRef} className="absolute inset-0 m-auto block h-auto max-h-full w-auto max-w-full shadow-[0_24px_80px_rgba(0,0,0,.65)]"/><canvas ref={overlayRef} onPointerDown={startBrush} onPointerMove={moveBrush} onPointerUp={finishBrush} onPointerCancel={finishBrush} className={`absolute inset-0 m-auto block h-auto max-h-full w-auto max-w-full touch-none ${selectedMask?.type==='brush'?'cursor-crosshair':'pointer-events-none'}`}/></div>:<button onClick={()=>imageInput.current?.click()} className="relative flex w-[min(460px,90%)] flex-col items-center rounded-2xl border border-dashed border-white/20 bg-white/[.025] px-10 py-14"><span className="mb-5 grid h-14 w-14 place-items-center rounded-2xl bg-[#e7ff46] text-2xl text-black">＋</span><span className="text-sm font-semibold">Bắt đầu với một bức ảnh</span><span className="mt-2 text-[10px] text-white/40">Kéo thả hoặc chọn JPG, PNG, WebP</span></button>}{image&&<button onPointerDown={()=>setCompare(true)} onPointerUp={()=>setCompare(false)} onPointerLeave={()=>setCompare(false)} className="absolute bottom-5 rounded-full border border-white/10 bg-black/60 px-4 py-2 text-[10px] text-white/65 backdrop-blur">Giữ để xem ảnh gốc</button>}{previewDoc&&<div className="absolute left-5 top-5 rounded-full bg-[#e7ff46] px-3 py-1.5 text-[9px] font-bold text-black">AI PREVIEW · chưa áp dụng</div>}</section>
      <aside className="min-h-0 overflow-y-auto border-l border-white/10 bg-[#17181b]"><div className="border-b border-white/10 p-4"><div className="mb-3 flex justify-between"><h2 className="text-xs font-semibold">Presets</h2><span className="text-[9px] text-[#e7ff46]/60">{selectedMask?selectedMask.name:'Toàn ảnh'}</span></div><div className="grid grid-cols-2 gap-2">{presets.map(p=><button key={p.name} onClick={()=>applyPreset(p)} className="rounded-lg border border-white/10 px-3 py-2.5 text-left text-[10px] text-white/60 hover:border-[#e7ff46]/30">{p.name}</button>)}</div></div><div className="p-4"><div className="mb-5 flex justify-between"><h2 className="text-[10px] font-semibold uppercase tracking-wider text-white/70">{selectedMask?'Điều chỉnh vùng':'Điều chỉnh toàn ảnh'}</h2><button onClick={()=>{editor.dispatch(ADJUSTMENT_KEYS.map(k=>editCommand(k,0,selectedMaskId)),'Đặt lại');setDraft(null)}} className="text-[9px] text-white/35">Đặt lại</button></div><div className="space-y-4">{ADJUSTMENT_KEYS.map((key,index)=>{const c=CONTROL_DEFINITIONS[key],value=valueFor(key);return <div key={key} className={index===6||index===10?'border-t border-white/10 pt-4':''}><div className="mb-1.5 flex justify-between text-[10px]"><label htmlFor={key} className="text-white/55">{c.label}</label><span className="font-mono text-white/35">{value>0?'+':''}{value}{c.unit==='EV'?' EV':''}</span></div><input id={key} className="adjustment-range" type="range" min={c.min} max={c.max} step={c.step} value={value} onChange={e=>setDraft(v=>({...activeAdjustments,...(v||{}),[key]:Number(e.target.value)}))} onPointerUp={()=>commit(key,value)}/></div>})}</div></div></aside>
      {devOpen&&<DeveloperPanel onPreview={async plan=>{await previewPlan(plan)}} onApply={applyPlan} onApplyCommand={applySingle} onClose={()=>{setDevOpen(false);setPreviewDoc(null)}}/>}
      {aiOpen&&image&&<AiPanel key={editor.document.id} onSelectRegion={id=>{setSelectedMaskId(id);setShowOverlay(true);setDraft(null);setPreviewDoc(null);}} image={image} document={editor.document} onPreview={previewPlan} onApply={applyPlan} onClose={()=>{setAiOpen(false);setPreviewDoc(null)}}/>}
      {exportOpen&&image&&<ExportPanel image={image} document={editor.document} onClose={()=>setExportOpen(false)}/>}
    </div>{notice&&<button onClick={()=>setNotice('')} className="absolute bottom-10 left-1/2 z-50 -translate-x-1/2 rounded-lg border border-white/10 bg-[#222428] px-4 py-2 text-[10px] shadow-xl">{notice} · bấm để đóng</button>}<footer className="flex h-12 shrink-0 items-center justify-between border-t border-white/10 bg-[#17181b] px-4 text-[8px] text-white/25"><span>Mask engine · WebGL2 · autosave IndexedDB</span><div className="flex items-center gap-3"><div role="group" aria-label="Điều khiển zoom ảnh" className="flex items-center gap-1">
<button type="button" aria-label="Thu nhỏ ảnh" title="Thu nhỏ" disabled={!image||viewport.zoom<=.1} onClick={()=>stepZoom(-1)} className="h-8 w-8 rounded-lg border border-white/15 text-xl text-white/80 hover:bg-white/10 focus-visible:outline-2 focus-visible:outline-[#e7ff46] disabled:opacity-25">−</button>
<output aria-label="Mức zoom so với vừa khung" className="min-w-14 text-center text-xs tabular-nums text-white/70">{Math.round(viewport.zoom*100)}%</output>
<button type="button" aria-label="Phóng to ảnh" title="Phóng to" disabled={!image||viewport.zoom>=8} onClick={()=>stepZoom(1)} className="h-8 w-8 rounded-lg border border-white/15 text-xl text-white/80 hover:bg-white/10 focus-visible:outline-2 focus-visible:outline-[#e7ff46] disabled:opacity-25">+</button>
<button type="button" disabled={!image} onClick={resetViewport} title="Hiển thị toàn bộ ảnh" className="ml-2 h-8 rounded-lg bg-white/5 px-3 text-xs text-[#e7ff46] hover:bg-white/10 disabled:opacity-25">Vừa khung</button>
</div><span>⌘/Ctrl + Space kéo: zoom · Space kéo: di chuyển · ⌘/Ctrl+0: vừa khung</span></div></footer><input ref={imageInput} type="file" accept="image/*" className="hidden" onChange={(e:ChangeEvent<HTMLInputElement>)=>selectImage(e.target.files?.[0])}/><input ref={projectInput} type="file" accept="application/json,.json" className="hidden" onChange={(e:ChangeEvent<HTMLInputElement>)=>importProject(e.target.files?.[0])}/>
  </main>;
}
