'use client';
import { ChangeEvent, DragEvent, useCallback, useEffect, useRef, useState } from 'react';
import { DeveloperPanel } from '@/components/developer-panel';
import { exportRenderedImage, renderImage } from '@/lib/editor/render';
import { parseProject, serializeProject } from '@/lib/editor/persistence';
import { CONTROL_DEFINITIONS } from '@/lib/editor/tools';
import { ADJUSTMENT_KEYS, Adjustments, EditCommand, EditPlan, INITIAL_ADJUSTMENTS, createId } from '@/lib/editor/types';
import { useEditor } from '@/lib/editor/use-editor';

const presets=[
  {name:'Tự nhiên',values:{contrast:8,vibrance:12,shadows:8}},{name:'Điện ảnh',values:{contrast:22,saturation:-12,temperature:-8,vignette:24}},
  {name:'Ấm áp',values:{temperature:24,tint:5,vibrance:16}},{name:'Đen trắng',values:{saturation:-100,contrast:18,clarity:12}},
] satisfies {name:string;values:Partial<Adjustments>}[];

function command(key:keyof Adjustments,value:number,origin:EditCommand['origin']='user'):EditCommand{return{id:createId('cmd'),version:1,tool:`adjust.${key}`,target:{type:'document'},parameters:{value},origin};}
function download(blob:Blob,name:string){const url=URL.createObjectURL(blob),link=window.document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),500);}

export default function Home(){
  const editor=useEditor(); const canvasRef=useRef<HTMLCanvasElement>(null); const imageInput=useRef<HTMLInputElement>(null); const projectInput=useRef<HTMLInputElement>(null); const imageRef=useRef<HTMLImageElement|null>(null); const objectUrl=useRef<string|undefined>(undefined);
  const [image,setImage]=useState<HTMLImageElement|null>(null); const [draft,setDraft]=useState<Adjustments|null>(null); const [preview,setPreview]=useState<Adjustments|null>(null); const [compare,setCompare]=useState(false); const [dragging,setDragging]=useState(false); const [devOpen,setDevOpen]=useState(false); const [notice,setNotice]=useState('');
  const loadBlob=useCallback((blob:Blob,name:string,persist=true)=>{if(objectUrl.current)URL.revokeObjectURL(objectUrl.current);const url=URL.createObjectURL(blob);objectUrl.current=url;const next=new Image();next.onload=()=>{imageRef.current=next;setImage(next);if(persist)editor.setImage(blob,name);};next.src=url;},[editor]);
  useEffect(()=>{if(!editor.ready||image)return;const stored=editor.getStoredImage();if(stored.blob)loadBlob(stored.blob,stored.name||editor.document.name,false);},[editor.ready,image,editor,loadBlob]);
  useEffect(()=>{const canvas=canvasRef.current;if(canvas&&imageRef.current)renderImage(canvas,imageRef.current,compare?INITIAL_ADJUSTMENTS:(preview||draft||editor.document.adjustments));},[image,draft,preview,compare,editor.document.adjustments]);
  useEffect(()=>{const key=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='z'){event.preventDefault();if(event.shiftKey)editor.redo();else editor.undo();}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[editor]);

  async function commit(key:keyof Adjustments,value:number){try{await editor.dispatch([command(key,value)],`Điều chỉnh ${CONTROL_DEFINITIONS[key].label}`);setDraft(null);setPreview(null);}catch(error){setNotice(error instanceof Error?error.message:'Không thể áp dụng');}}
  async function applyPreset(preset:(typeof presets)[number]){const commands=Object.entries({...INITIAL_ADJUSTMENTS,...preset.values}).map(([key,value])=>command(key as keyof Adjustments,value,'preset'));await editor.dispatch(commands,`Preset ${preset.name}`);setDraft(null);setPreview(null);}
  function selectImage(file?:File){if(file?.type.startsWith('image/'))loadBlob(file,file.name);}
  async function exportImage(){if(!imageRef.current)return;const blob=await exportRenderedImage(imageRef.current,editor.document.adjustments);download(blob,`${editor.document.name.replace(/\.[^.]+$/,'')}-edited.jpg`);}
  function exportProject(){download(new Blob([serializeProject(editor.document,editor.transactions,editor.historyIndex)],{type:'application/json'}),`${editor.document.name.replace(/\.[^.]+$/,'')}.openphoto.json`);}
  async function importProject(file?:File){if(!file)return;try{editor.restore(parseProject(await file.text()));setPreview(null);setNotice('Đã nạp project. Chọn lại ảnh gốc nếu project này dùng ảnh khác.');}catch(error){setNotice(error instanceof Error?error.message:'Không thể mở project');}}
  async function previewPlan(plan:EditPlan){const result=await editor.preview(plan.commands);setPreview(result.document.adjustments);}
  async function applyPlan(plan:EditPlan){await editor.dispatch(plan.commands,plan.title);setPreview(null);}
  async function applySingle(value:EditCommand){await editor.dispatch([value],`AI · ${value.tool}`);setPreview(null);}
  function drop(event:DragEvent){event.preventDefault();setDragging(false);selectImage(event.dataTransfer.files[0]);}

  return <main className="flex h-dvh min-h-[620px] flex-col overflow-hidden bg-[#111214] text-[#eee]">
    <header className="flex h-14 shrink-0 items-center justify-between border-b border-white/10 bg-[#17181b] px-4"><div className="flex items-center gap-3"><div className="grid h-8 w-8 place-items-center rounded-lg bg-[#e7ff46] font-black text-black">O</div><div><div className="text-sm font-semibold">OpenPhoto</div><div className="max-w-48 truncate text-[9px] text-white/40">{editor.document.name} · schema v{editor.document.schemaVersion}</div></div></div>
      <div className="flex items-center gap-1 rounded-lg bg-black/20 p-1"><button onClick={()=>{editor.undo();setDraft(null);setPreview(null)}} disabled={editor.historyIndex<0} className="toolbar-button">↶</button><button onClick={()=>{editor.redo();setDraft(null);setPreview(null)}} disabled={editor.historyIndex>=editor.transactions.length-1} className="toolbar-button">↷</button><span className="mx-1 h-5 w-px bg-white/10"/><span className="px-2 text-[9px] text-white/35">{editor.historyIndex+1}/{editor.transactions.length} thao tác</span></div>
      <div className="flex gap-2"><button onClick={exportProject} className="rounded-lg border border-white/10 px-3 py-2 text-[10px] hover:bg-white/5">Lưu project</button><button onClick={()=>projectInput.current?.click()} className="rounded-lg border border-white/10 px-3 py-2 text-[10px] hover:bg-white/5">Mở project</button><button onClick={()=>imageInput.current?.click()} className="rounded-lg border border-white/15 px-3 py-2 text-[10px] hover:bg-white/5">Mở ảnh</button><button disabled={!image} onClick={exportImage} className="rounded-lg bg-[#e7ff46] px-4 py-2 text-[10px] font-bold text-black disabled:opacity-30">Xuất JPG</button></div></header>
    <div className="grid min-h-0 flex-1 grid-cols-[56px_minmax(0,1fr)_320px]">
      <aside className="flex flex-col items-center gap-2 border-r border-white/10 bg-[#17181b] py-4">{['◫','⌁','◐'].map((icon,index)=><button key={icon} className={`grid h-9 w-9 place-items-center rounded-lg text-lg ${index===2?'bg-[#e7ff46]/12 text-[#e7ff46]':'text-white/30'}`}>{icon}</button>)}<button onClick={()=>setDevOpen(true)} className={`grid h-9 w-9 place-items-center rounded-lg text-lg ${devOpen?'bg-[#e7ff46] text-black':'text-[#e7ff46] hover:bg-[#e7ff46]/10'}`} title="AI Tool Lab">✦</button><div className="mt-auto text-[8px] uppercase tracking-[.16em] text-white/20 [writing-mode:vertical-rl]">Command-first editor</div></aside>
      <section onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={drop} className={`relative grid min-h-0 place-items-center overflow-hidden p-8 ${dragging?'bg-[#e7ff46]/5':'bg-[#0d0e10]'}`}><div className="absolute inset-0 editor-grid opacity-30"/>{image?<canvas ref={canvasRef} className="relative max-h-full max-w-full shadow-[0_24px_80px_rgba(0,0,0,.65)]"/>:<button onClick={()=>imageInput.current?.click()} className="relative flex w-[min(460px,90%)] flex-col items-center rounded-2xl border border-dashed border-white/20 bg-white/[.025] px-10 py-14"><span className="mb-5 grid h-14 w-14 place-items-center rounded-2xl bg-[#e7ff46] text-2xl text-black">＋</span><span className="text-sm font-semibold">Bắt đầu với một bức ảnh</span><span className="mt-2 text-[10px] text-white/40">Kéo thả hoặc chọn JPG, PNG, WebP</span></button>}
        {image&&<button onPointerDown={()=>setCompare(true)} onPointerUp={()=>setCompare(false)} onPointerLeave={()=>setCompare(false)} className="absolute bottom-5 rounded-full border border-white/10 bg-black/60 px-4 py-2 text-[10px] text-white/65 backdrop-blur">Giữ để xem ảnh gốc</button>}{preview&&<div className="absolute left-5 top-5 flex items-center gap-2 rounded-full bg-[#e7ff46] px-3 py-1.5 text-[9px] font-bold text-black"><span className="h-1.5 w-1.5 rounded-full bg-black"/>AI PREVIEW · chưa áp dụng</div>}
      </section>
      <aside className="min-h-0 overflow-y-auto border-l border-white/10 bg-[#17181b]"><div className="border-b border-white/10 p-4"><div className="mb-3 flex justify-between"><h2 className="text-xs font-semibold">Presets</h2><span className="text-[9px] text-white/30">qua command bus</span></div><div className="grid grid-cols-2 gap-2">{presets.map(p=><button key={p.name} onClick={()=>applyPreset(p)} className="rounded-lg border border-white/10 px-3 py-2.5 text-left text-[10px] text-white/60 hover:border-[#e7ff46]/30">{p.name}</button>)}</div></div>
        <div className="p-4"><div className="mb-5 flex justify-between"><h2 className="text-[10px] font-semibold uppercase tracking-wider text-white/70">Điều chỉnh</h2><button onClick={()=>{editor.dispatch(ADJUSTMENT_KEYS.map(k=>command(k,0)),'Đặt lại');setDraft(null)}} className="text-[9px] text-white/35 hover:text-[#e7ff46]">Đặt lại</button></div><div className="space-y-4">{ADJUSTMENT_KEYS.map((key,index)=>{const c=CONTROL_DEFINITIONS[key],value=draft?.[key]??editor.document.adjustments[key];return <div key={key} className={index===6||index===10?'border-t border-white/10 pt-4':''}><div className="mb-1.5 flex justify-between text-[10px]"><label htmlFor={key} className="text-white/55">{c.label}</label><span className="font-mono text-white/35">{value>0?'+':''}{value}{c.unit==='EV'?' EV':''}</span></div><input id={key} type="range" min={c.min} max={c.max} step={c.step} value={value} onChange={e=>setDraft(v=>({...editor.document.adjustments,...(v||{}),[key]:Number(e.target.value)}))} onPointerUp={()=>commit(key,value)} className="adjustment-range"/></div>})}</div></div>
      </aside>
      {devOpen&&<DeveloperPanel onPreview={previewPlan} onApply={applyPlan} onApplyCommand={applySingle} onClose={()=>{setDevOpen(false);setPreview(null)}}/>}
    </div>
    {notice&&<button onClick={()=>setNotice('')} className="absolute bottom-10 left-1/2 z-50 -translate-x-1/2 rounded-lg border border-white/10 bg-[#222428] px-4 py-2 text-[10px] shadow-xl">{notice} · bấm để đóng</button>}
    <footer className="flex h-7 items-center justify-between border-t border-white/10 bg-[#17181b] px-4 text-[8px] text-white/25"><span>WebGL2 · autosave IndexedDB · ảnh không rời thiết bị</span><span>✦ AI Tool Lab · ⌘Z undo</span></footer>
    <input ref={imageInput} type="file" accept="image/*" className="hidden" onChange={(e:ChangeEvent<HTMLInputElement>)=>selectImage(e.target.files?.[0])}/><input ref={projectInput} type="file" accept="application/json,.json" className="hidden" onChange={(e:ChangeEvent<HTMLInputElement>)=>importProject(e.target.files?.[0])}/>
  </main>;
}
