'use client';
import { useState } from 'react';
import { EditPlan } from '@/lib/editor/types';
import { validatePlan } from '@/lib/editor/dispatcher';

function makePreview(image:HTMLImageElement){const max=1280,scale=Math.min(1,max/Math.max(image.naturalWidth,image.naturalHeight)),canvas=document.createElement('canvas');canvas.width=Math.round(image.naturalWidth*scale);canvas.height=Math.round(image.naturalHeight*scale);const context=canvas.getContext('2d');if(!context)throw new Error('Không thể tạo preview.');context.drawImage(image,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/jpeg',.82);}

export function AiPanel({image,onPreview,onApply,onClose}:{image:HTMLImageElement;onPreview:(plan:EditPlan)=>Promise<void>;onApply:(plan:EditPlan)=>Promise<void>;onClose:()=>void}){
  const[prompt,setPrompt]=useState('Chỉnh ảnh tự nhiên, cân bằng ánh sáng và màu sắc. Tự nhận diện và chỉnh riêng từng vùng nếu cần.');
  const[plan,setPlan]=useState<EditPlan|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('Ảnh preview thu nhỏ sẽ được gửi tới AI. Ảnh gốc không được gửi.');
  async function analyze(){setBusy(true);setPlan(null);setMessage('AI đang quan sát ảnh và lập kế hoạch…');try{const response=await fetch('/api/ai/edit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt,image:makePreview(image)})}),data=await response.json() as {plan?:EditPlan;error?:string};if(!response.ok||!data.plan)throw new Error(data.error||'AI không trả về kế hoạch.');validatePlan(data.plan);await onPreview(data.plan);setPlan(data.plan);setMessage(`Đã tạo ${data.plan.commands.length} lệnh · đang xem trước, chưa áp dụng.`);}catch(error){setMessage(error instanceof Error?error.message:'Không thể gọi AI.');}finally{setBusy(false);}}
  async function apply(){if(!plan)return;setBusy(true);try{await onApply(plan);setMessage('Đã áp dụng kế hoạch dưới dạng một transaction.');onClose();}catch(error){setMessage(error instanceof Error?error.message:'Không thể áp dụng.');}finally{setBusy(false);}}
  return <section className="absolute inset-y-0 right-0 z-30 flex w-[430px] max-w-[90vw] flex-col border-l border-white/10 bg-[#151619]/98 shadow-2xl backdrop-blur-xl"><header className="flex items-center justify-between border-b border-white/10 px-4 py-3"><div><div className="text-xs font-semibold text-[#e7ff46]">AI EDIT</div><div className="mt-1 text-[10px] text-white/40">Phân tích ảnh · tạo vùng · chỉnh màu</div></div><button onClick={onClose} className="toolbar-button">×</button></header><div className="flex-1 overflow-y-auto p-4"><label className="mb-2 block text-[10px] font-semibold uppercase tracking-wider text-white/45">Bạn muốn ảnh trông như thế nào?</label><textarea value={prompt} onChange={event=>setPrompt(event.target.value)} maxLength={2000} className="h-28 w-full resize-none rounded-xl border border-white/10 bg-black/30 p-3 text-xs leading-5 text-white/80 outline-none focus:border-[#e7ff46]/45"/><button disabled={busy||!prompt.trim()} onClick={analyze} className="mt-3 w-full rounded-lg bg-[#e7ff46] py-2.5 text-[10px] font-bold text-black disabled:opacity-40">{busy?'Đang phân tích…':'Phân tích & tạo preview'}</button><div className="mt-3 rounded-lg bg-white/[.035] px-3 py-2 text-[10px] leading-4 text-white/50">{message}</div>{plan&&<div className="mt-5"><div className="flex items-center justify-between"><h3 className="text-xs font-semibold">{plan.title}</h3><span className="rounded-full bg-white/5 px-2 py-1 text-[9px] text-white/45">{Math.round(plan.confidence*100)}%</span></div><p className="mt-2 text-[10px] leading-4 text-white/45">{plan.rationale}</p><div className="mt-3 space-y-2">{plan.commands.map(command=><div key={command.id} className="rounded-lg border border-white/8 bg-white/[.02] p-2.5"><div className="font-mono text-[10px] text-[#e7ff46]/80">{command.tool}</div><div className="mt-1 text-[9px] text-white/35">{command.target.type==='mask'?`Vùng: ${command.target.id}`:'Toàn ảnh'}{command.parameters.value!==undefined?` · ${String(command.parameters.value)}`:''}</div></div>)}</div></div>}</div><footer className="grid grid-cols-2 gap-2 border-t border-white/10 p-4"><button onClick={onClose} className="rounded-lg border border-white/10 py-2 text-[10px]">Hủy</button><button disabled={!plan||busy} onClick={apply} className="rounded-lg bg-[#e7ff46] py-2 text-[10px] font-bold text-black disabled:opacity-30">Duyệt & áp dụng</button></footer></section>;
}
