'use client';
import { useEffect, useRef, useState } from 'react';
import { EditPlan } from '@/lib/editor/types';
import { AiEditingHarness, ImageAnalysis } from '@/lib/ai/harness';

export function AiPanel({image,document,onPreview,onApply,onClose}:{image:HTMLImageElement;document:import('@/lib/editor/types').EditorDocument;onPreview:(plan:EditPlan)=>Promise<import('@/lib/editor/types').EditorDocument>;onApply:(plan:EditPlan)=>Promise<void>;onClose:()=>void}){
  const harness=useRef(new AiEditingHarness());useEffect(()=>()=>harness.current.cancel(),[]);
  const[prompt,setPrompt]=useState('Chỉnh ảnh tự nhiên, cân bằng ánh sáng và màu sắc. Tự nhận diện và chỉnh riêng từng vùng nếu cần.');
  const[plan,setPlan]=useState<EditPlan|null>(null),[analysis,setAnalysis]=useState<ImageAnalysis|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('Harness sẽ tự phân tích ảnh, lập kế hoạch và chạy thử. Ảnh gốc không được gửi.');
  async function analyze(){setBusy(true);setPlan(null);try{const result=await harness.current.process({image,prompt,document,preview:onPreview,onProgress:progress=>setMessage(progress.message)});setPlan(result.plan);setAnalysis(result.analysis);}catch(error){setMessage(error instanceof Error?(error.name==='AbortError'?'Đã hủy phân tích.':error.message):'Không thể gọi AI.');}finally{setBusy(false);}}
  async function apply(){if(!plan)return;setBusy(true);try{await onApply(plan);setMessage('Đã áp dụng kế hoạch dưới dạng một transaction.');onClose();}catch(error){setMessage(error instanceof Error?error.message:'Không thể áp dụng.');}finally{setBusy(false);}}
  return <section className="absolute inset-y-0 right-0 z-30 flex w-[430px] max-w-[90vw] flex-col border-l border-white/10 bg-[#151619]/98 shadow-2xl backdrop-blur-xl"><header className="flex items-center justify-between border-b border-white/10 px-4 py-3"><div><div className="text-xs font-semibold text-[#e7ff46]">AI EDIT HARNESS</div><div className="mt-1 text-[10px] text-white/40">Phân tích · điều phối · kiểm tra · preview</div></div><button onClick={onClose} className="toolbar-button">×</button></header><div className="flex-1 overflow-y-auto p-4"><label className="mb-2 block text-[10px] font-semibold uppercase tracking-wider text-white/45">Bạn muốn ảnh trông như thế nào?</label><textarea value={prompt} onChange={event=>setPrompt(event.target.value)} maxLength={2000} className="h-28 w-full resize-none rounded-xl border border-white/10 bg-black/30 p-3 text-xs leading-5 text-white/80 outline-none focus:border-[#e7ff46]/45"/><button disabled={busy||!prompt.trim()} onClick={analyze} className="mt-3 w-full rounded-lg bg-[#e7ff46] py-2.5 text-[10px] font-bold text-black disabled:opacity-40">{busy?'Harness đang xử lý…':'Tự phân tích & tạo preview'}</button><div className="mt-3 rounded-lg bg-white/[.035] px-3 py-2 text-[10px] leading-4 text-white/50">{message}</div>{analysis&&<div className="mt-2 grid grid-cols-3 gap-2 text-center text-[9px] text-white/35"><div className="rounded bg-white/[.025] p-2">Sáng<br/><b className="text-white/60">{Math.round(analysis.meanLuminance*100)}%</b></div><div className="rounded bg-white/[.025] p-2">Shadow clip<br/><b className="text-white/60">{Math.round(analysis.shadowRatio*100)}%</b></div><div className="rounded bg-white/[.025] p-2">Highlight clip<br/><b className="text-white/60">{Math.round(analysis.highlightRatio*100)}%</b></div></div>}{plan&&<div className="mt-5"><div className="flex items-center justify-between"><h3 className="text-xs font-semibold">{plan.title}</h3><span className="rounded-full bg-white/5 px-2 py-1 text-[9px] text-white/45">{Math.round(plan.confidence*100)}%</span></div><p className="mt-2 text-[10px] leading-4 text-white/45">{plan.rationale}</p><div className="mt-3 space-y-2">{plan.commands.map(command=><div key={command.id} className="rounded-lg border border-white/8 bg-white/[.02] p-2.5"><div className="font-mono text-[10px] text-[#e7ff46]/80">{command.tool}</div><div className="mt-1 text-[9px] text-white/35">{command.target.type==='mask'?`Vùng: ${command.target.id}`:'Toàn ảnh'}{command.parameters.value!==undefined?` · ${String(command.parameters.value)}`:''}</div></div>)}</div></div>}</div><footer className="grid grid-cols-2 gap-2 border-t border-white/10 p-4"><button onClick={()=>{harness.current.cancel();onClose();}} className="rounded-lg border border-white/10 py-2 text-[10px]">Hủy</button><button disabled={!plan||busy} onClick={apply} className="rounded-lg bg-[#e7ff46] py-2 text-[10px] font-bold text-black disabled:opacity-30">Duyệt & áp dụng</button></footer></section>;
}
