import { Adjustments, EditorDocument, MaskDefinition } from './types';

const vertexShader=`#version 300 es
in vec2 a_position;in vec2 a_texCoord;out vec2 v_texCoord;void main(){gl_Position=vec4(a_position,0.,1.);v_texCoord=a_texCoord;}`;
const fragmentShader=`#version 300 es
precision highp float;uniform sampler2D u_image;uniform float u_exposure,u_contrast,u_highlights,u_shadows,u_whites,u_blacks,u_temperature,u_tint,u_vibrance,u_saturation,u_clarity,u_vignette;in vec2 v_texCoord;out vec4 outColor;
void main(){vec4 src=texture(u_image,v_texCoord);vec3 c=src.rgb*pow(2.,u_exposure);float light=(max(max(c.r,c.g),c.b)+min(min(c.r,c.g),c.b))*.5;float sm=pow(1.-clamp(light,0.,1.),2.);float hm=pow(clamp(light,0.,1.),2.);float tone=u_shadows*sm*.28+u_highlights*hm*.22+u_whites*hm*.13+u_blacks*sm*.11;c+=tone;c+=vec3(u_temperature+u_tint,-u_tint*.5,-u_temperature+u_tint);float cf=(1.015686*(u_contrast+1.))/(1.015686-u_contrast);c=cf*(c-.5)+.5;float mid=1.-abs(light-.5)*2.;c=(c-.5)*(1.+u_clarity*mid*.45)+.5;float gray=dot(c,vec3(.299,.587,.114));float mx=max(max(c.r,c.g),c.b);float avg=(c.r+c.g+c.b)/3.;float vib=1.+u_vibrance*(1.-abs(mx-avg));c=vec3(gray)+(c-vec3(gray))*((1.+u_saturation)*vib);vec2 centered=v_texCoord-.5;float edge=smoothstep(.24,.72,length(centered));c*=1.-edge*u_vignette*.75;outColor=vec4(clamp(c,0.,1.),src.a);}`;

type Pipeline={canvas:HTMLCanvasElement;gl:WebGL2RenderingContext;program:WebGLProgram;texture:WebGLTexture;source:HTMLImageElement|null;uniforms:Record<string,WebGLUniformLocation|null>};
let pipeline:Pipeline|null=null,layerCanvas:HTMLCanvasElement|null=null,fallbackCanvas:HTMLCanvasElement|null=null;
const maskCache=new WeakMap<MaskDefinition,Map<string,HTMLCanvasElement>>();

function shader(gl:WebGL2RenderingContext,type:number,source:string){const value=gl.createShader(type);if(!value)throw new Error('Không thể tạo shader.');gl.shaderSource(value,source);gl.compileShader(value);if(!gl.getShaderParameter(value,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(value)||'Shader lỗi.');return value;}
function createPipeline():Pipeline|null{const canvas=document.createElement('canvas'),gl=canvas.getContext('webgl2',{preserveDrawingBuffer:true,antialias:false,alpha:true});if(!gl)return null;const program=gl.createProgram(),texture=gl.createTexture();if(!program||!texture)return null;gl.attachShader(program,shader(gl,gl.VERTEX_SHADER,vertexShader));gl.attachShader(program,shader(gl,gl.FRAGMENT_SHADER,fragmentShader));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw new Error('Không thể khởi tạo WebGL.');gl.useProgram(program);const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,0,1,1,-1,1,1,-1,1,0,0,-1,1,0,0,1,-1,1,1,1,1,1,0]),gl.STATIC_DRAW);const pos=gl.getAttribLocation(program,'a_position'),tex=gl.getAttribLocation(program,'a_texCoord');gl.enableVertexAttribArray(pos);gl.vertexAttribPointer(pos,2,gl.FLOAT,false,16,0);gl.enableVertexAttribArray(tex);gl.vertexAttribPointer(tex,2,gl.FLOAT,false,16,8);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,texture);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.uniform1i(gl.getUniformLocation(program,'u_image'),0);const names=['exposure','contrast','highlights','shadows','whites','blacks','temperature','tint','vibrance','saturation','clarity','vignette'],uniforms=Object.fromEntries(names.map(name=>[name,gl.getUniformLocation(program,`u_${name}`)]));return{canvas,gl,program,texture,source:null,uniforms};}
function renderWebGL(image:HTMLImageElement,width:number,height:number,a:Adjustments){pipeline||=createPipeline();if(!pipeline)return null;const{canvas,gl,program,texture,uniforms}=pipeline;if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height;}gl.viewport(0,0,width,height);gl.useProgram(program);gl.bindTexture(gl.TEXTURE_2D,texture);if(pipeline.source!==image){gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,image);pipeline.source=image;}const values:Record<string,number>={exposure:a.exposure,contrast:a.contrast/100,highlights:a.highlights/100,shadows:a.shadows/100,whites:a.whites/100,blacks:a.blacks/100,temperature:a.temperature/500,tint:a.tint/500,vibrance:a.vibrance/100,saturation:a.saturation/100,clarity:a.clarity/100,vignette:a.vignette/100};for(const[name,value]of Object.entries(values))gl.uniform1f(uniforms[name],value);gl.drawArrays(gl.TRIANGLES,0,6);return canvas;}
function renderFallback(image:HTMLImageElement,width:number,height:number,a:Adjustments){fallbackCanvas||=document.createElement('canvas');fallbackCanvas.width=width;fallbackCanvas.height=height;const ctx=fallbackCanvas.getContext('2d');if(!ctx)throw new Error('Canvas không khả dụng.');ctx.clearRect(0,0,width,height);ctx.filter=`brightness(${Math.pow(2,a.exposure)*100}%) contrast(${100+a.contrast}%) saturate(${100+a.saturation+a.vibrance*.5}%)`;ctx.drawImage(image,0,0,width,height);ctx.filter='none';return fallbackCanvas;}
function renderVariant(image:HTMLImageElement,width:number,height:number,a:Adjustments){try{return renderWebGL(image,width,height,a)||renderFallback(image,width,height,a);}catch{pipeline=null;return renderFallback(image,width,height,a);}}
function combined(global:Adjustments,local:Adjustments):Adjustments{return Object.fromEntries(Object.keys(global).map(key=>[key,global[key as keyof Adjustments]+local[key as keyof Adjustments]])) as Adjustments;}

export function createMaskCanvas(mask:MaskDefinition,width:number,height:number){const key=`${width}x${height}`,cached=maskCache.get(mask)?.get(key);if(cached)return cached;const hard=document.createElement('canvas');hard.width=width;hard.height=height;const ctx=hard.getContext('2d');if(!ctx)return hard;ctx.fillStyle='white';ctx.strokeStyle='white';ctx.lineCap='round';ctx.lineJoin='round';const g=mask.geometry;
if(mask.type==='brush'){const strokes=g.strokes||[g.points||[]],size=(g.brushSize||.08)*Math.min(width,height);for(const points of strokes){if(points.length===1){ctx.beginPath();ctx.arc(points[0].x*width,points[0].y*height,size/2,0,Math.PI*2);ctx.fill();}else if(points.length>1){ctx.lineWidth=size;ctx.beginPath();ctx.moveTo(points[0].x*width,points[0].y*height);for(const point of points.slice(1))ctx.lineTo(point.x*width,point.y*height);ctx.stroke();}}}
if(mask.type==='radial'){const center=g.center||{x:.5,y:.5},rx=(g.radiusX||.3)*width,ry=(g.radiusY||.3)*height;ctx.save();ctx.translate(center.x*width,center.y*height);ctx.scale(1,ry/rx);const gradient=ctx.createRadialGradient(0,0,rx*(1-mask.feather),0,0,rx);gradient.addColorStop(0,'white');gradient.addColorStop(1,'transparent');ctx.fillStyle=gradient;ctx.beginPath();ctx.arc(0,0,rx,0,Math.PI*2);ctx.fill();ctx.restore();}
if(mask.type==='linear'){const start=g.start||{x:.5,y:.2},end=g.end||{x:.5,y:.8},gradient=ctx.createLinearGradient(start.x*width,start.y*height,end.x*width,end.y*height),edge=Math.max(0,Math.min(.95,mask.feather));gradient.addColorStop(0,'transparent');gradient.addColorStop(Math.max(.01,1-edge),'white');gradient.addColorStop(1,'white');ctx.fillStyle=gradient;ctx.fillRect(0,0,width,height);}
if(mask.type==='semantic'&&g.polygon&&g.polygon.length>=3){ctx.beginPath();ctx.moveTo(g.polygon[0].x*width,g.polygon[0].y*height);for(const point of g.polygon.slice(1))ctx.lineTo(point.x*width,point.y*height);ctx.closePath();ctx.fill();}
let result=hard;if((mask.type==='brush'||mask.type==='semantic')&&mask.feather>0){result=document.createElement('canvas');result.width=width;result.height=height;const blur=result.getContext('2d');if(blur){blur.filter=`blur(${mask.feather*Math.min(width,height)*.08}px)`;blur.drawImage(hard,0,0);blur.filter='none';}}if(mask.inverted){const inverted=document.createElement('canvas');inverted.width=width;inverted.height=height;const inverse=inverted.getContext('2d');if(inverse){inverse.fillStyle='white';inverse.fillRect(0,0,width,height);inverse.globalCompositeOperation='destination-out';inverse.drawImage(result,0,0);result=inverted;}}if(mask.opacity<1){const faded=document.createElement('canvas');faded.width=width;faded.height=height;const fade=faded.getContext('2d');if(fade){fade.globalAlpha=mask.opacity;fade.drawImage(result,0,0);result=faded;}}const entries=maskCache.get(mask)||new Map<string,HTMLCanvasElement>();entries.set(key,result);maskCache.set(mask,entries);return result;}

export function renderImage(canvas:HTMLCanvasElement,image:HTMLImageElement,editorDocument:EditorDocument,maxDimension=1400){const scale=Math.min(1,maxDimension/Math.max(image.naturalWidth,image.naturalHeight)),width=Math.max(1,Math.round(image.naturalWidth*scale)),height=Math.max(1,Math.round(image.naturalHeight*scale));if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height;}const output=canvas.getContext('2d');if(!output)throw new Error('Canvas không khả dụng.');output.clearRect(0,0,width,height);output.drawImage(renderVariant(image,width,height,editorDocument.adjustments),0,0);for(const mask of editorDocument.masks){if(!mask.enabled)continue;const local=renderVariant(image,width,height,combined(editorDocument.adjustments,mask.adjustments));layerCanvas||=document.createElement('canvas');if(layerCanvas.width!==width||layerCanvas.height!==height){layerCanvas.width=width;layerCanvas.height=height;}const layer=layerCanvas.getContext('2d');if(!layer)continue;layer.globalCompositeOperation='source-over';layer.clearRect(0,0,width,height);layer.drawImage(local,0,0);layer.globalCompositeOperation='destination-in';layer.drawImage(createMaskCanvas(mask,width,height),0,0);output.drawImage(layerCanvas,0,0);}}
export function drawMaskOverlay(canvas:HTMLCanvasElement,mask:MaskDefinition|null,width:number,height:number){if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height;}const ctx=canvas.getContext('2d');if(!ctx)return;ctx.globalCompositeOperation='source-over';ctx.globalAlpha=1;ctx.clearRect(0,0,width,height);if(!mask)return;ctx.globalAlpha=.5;ctx.drawImage(createMaskCanvas(mask,width,height),0,0);ctx.globalCompositeOperation='source-in';ctx.fillStyle='#ff3568';ctx.fillRect(0,0,width,height);ctx.globalCompositeOperation='source-over';ctx.globalAlpha=1;}
export type ExportFormat='image/jpeg'|'image/png'|'image/webp';
export type ExportOptions={type:ExportFormat;quality:number;maxDimension:number;sharpening:0|1|2|3};

function applyOutputSharpening(source:HTMLCanvasElement,level:ExportOptions['sharpening']){if(level===0)return source;const canvas=document.createElement('canvas');canvas.width=source.width;canvas.height=source.height;const gl=canvas.getContext('webgl2',{preserveDrawingBuffer:true,antialias:false});if(!gl)return source;const vertex=`#version 300 es
in vec2 p;in vec2 t;out vec2 uv;void main(){gl_Position=vec4(p,0.,1.);uv=t;}`;const fragment=`#version 300 es
precision highp float;uniform sampler2D image;uniform vec2 pixel;uniform float amount;in vec2 uv;out vec4 color;void main(){vec4 c=texture(image,uv);vec3 edge=c.rgb*4.-texture(image,uv+vec2(pixel.x,0.)).rgb-texture(image,uv-vec2(pixel.x,0.)).rgb-texture(image,uv+vec2(0.,pixel.y)).rgb-texture(image,uv-vec2(0.,pixel.y)).rgb;color=vec4(clamp(c.rgb+edge*amount,0.,1.),c.a);}`;try{const program=gl.createProgram();if(!program)return source;gl.attachShader(program,shader(gl,gl.VERTEX_SHADER,vertex));gl.attachShader(program,shader(gl,gl.FRAGMENT_SHADER,fragment));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))return source;gl.useProgram(program);const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,0,1,1,-1,1,1,-1,1,0,0,-1,1,0,0,1,-1,1,1,1,1,1,0]),gl.STATIC_DRAW);const p=gl.getAttribLocation(program,'p'),t=gl.getAttribLocation(program,'t');gl.enableVertexAttribArray(p);gl.vertexAttribPointer(p,2,gl.FLOAT,false,16,0);gl.enableVertexAttribArray(t);gl.vertexAttribPointer(t,2,gl.FLOAT,false,16,8);const texture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,texture);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,source);gl.uniform1i(gl.getUniformLocation(program,'image'),0);gl.uniform2f(gl.getUniformLocation(program,'pixel'),1/source.width,1/source.height);gl.uniform1f(gl.getUniformLocation(program,'amount'),[0,.12,.22,.34][level]);gl.viewport(0,0,source.width,source.height);gl.drawArrays(gl.TRIANGLES,0,6);return canvas;}catch{return source;}}

export async function exportRenderedImage(image:HTMLImageElement,editorDocument:EditorDocument,options:Partial<ExportOptions>={}){const settings:ExportOptions={type:options.type||'image/jpeg',quality:options.quality??.97,maxDimension:options.maxDimension||Math.max(image.naturalWidth,image.naturalHeight),sharpening:options.sharpening??2};const probe=document.createElement('canvas').getContext('webgl2'),limit=probe?.getParameter(probe.MAX_TEXTURE_SIZE) as number|undefined;if(limit&&settings.maxDimension>limit)throw new Error(`GPU này chỉ hỗ trợ cạnh ảnh tối đa ${limit}px. Hãy giảm kích thước xuất.`);const canvas=document.createElement('canvas');renderImage(canvas,image,editorDocument,Math.min(settings.maxDimension,Math.max(image.naturalWidth,image.naturalHeight)));const output=applyOutputSharpening(canvas,settings.sharpening);return new Promise<Blob>((resolve,reject)=>output.toBlob(blob=>blob?resolve(blob):reject(new Error('Trình duyệt không hỗ trợ định dạng xuất này.')),settings.type,settings.type==='image/png'?undefined:settings.quality));}
