import { Adjustments, EditorDocument, MaskDefinition } from './types';

const vertexShader=`#version 300 es
in vec2 a_position;in vec2 a_texCoord;out vec2 v_texCoord;void main(){gl_Position=vec4(a_position,0.,1.);v_texCoord=a_texCoord;}`;
const fragmentShader=`#version 300 es
precision highp float;uniform sampler2D u_image;uniform float u_exposure,u_contrast,u_highlights,u_shadows,u_whites,u_blacks,u_temperature,u_tint,u_vibrance,u_saturation,u_clarity,u_vignette;in vec2 v_texCoord;out vec4 outColor;
void main(){vec4 src=texture(u_image,v_texCoord);vec3 c=src.rgb*pow(2.,u_exposure);float light=(max(max(c.r,c.g),c.b)+min(min(c.r,c.g),c.b))*.5;float sm=pow(1.-clamp(light,0.,1.),2.);float hm=pow(clamp(light,0.,1.),2.);float tone=u_shadows*sm*.28+u_highlights*hm*.22+u_whites*hm*.13+u_blacks*sm*.11;c+=tone;c+=vec3(u_temperature+u_tint,-u_tint*.5,-u_temperature+u_tint);float cf=(1.015686*(u_contrast+1.))/(1.015686-u_contrast);c=cf*(c-.5)+.5;float mid=1.-abs(light-.5)*2.;c=(c-.5)*(1.+u_clarity*mid*.45)+.5;float gray=dot(c,vec3(.299,.587,.114));float mx=max(max(c.r,c.g),c.b);float avg=(c.r+c.g+c.b)/3.;float vib=1.+u_vibrance*(1.-abs(mx-avg));c=vec3(gray)+(c-vec3(gray))*((1.+u_saturation)*vib);vec2 centered=v_texCoord-.5;float edge=smoothstep(.24,.72,length(centered));c*=1.-edge*u_vignette*.75;outColor=vec4(clamp(c,0.,1.),src.a);}`;

function shader(gl:WebGL2RenderingContext,type:number,source:string){const value=gl.createShader(type);if(!value)throw new Error('Không thể tạo shader.');gl.shaderSource(value,source);gl.compileShader(value);if(!gl.getShaderParameter(value,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(value)||'Shader lỗi.');return value;}
function renderWebGL(canvas:HTMLCanvasElement,image:HTMLImageElement,width:number,height:number,a:Adjustments){canvas.width=width;canvas.height=height;const gl=canvas.getContext('webgl2',{preserveDrawingBuffer:true});if(!gl)return false;const program=gl.createProgram();if(!program)return false;gl.attachShader(program,shader(gl,gl.VERTEX_SHADER,vertexShader));gl.attachShader(program,shader(gl,gl.FRAGMENT_SHADER,fragmentShader));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw new Error('Không thể khởi tạo WebGL.');gl.useProgram(program);const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,0,1,1,-1,1,1,-1,1,0,0,-1,1,0,0,1,-1,1,1,1,1,1,0]),gl.STATIC_DRAW);const pos=gl.getAttribLocation(program,'a_position'),tex=gl.getAttribLocation(program,'a_texCoord');gl.enableVertexAttribArray(pos);gl.vertexAttribPointer(pos,2,gl.FLOAT,false,16,0);gl.enableVertexAttribArray(tex);gl.vertexAttribPointer(tex,2,gl.FLOAT,false,16,8);const texture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,texture);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,image);const uniforms:Record<string,number>={u_exposure:a.exposure,u_contrast:a.contrast/100,u_highlights:a.highlights/100,u_shadows:a.shadows/100,u_whites:a.whites/100,u_blacks:a.blacks/100,u_temperature:a.temperature/500,u_tint:a.tint/500,u_vibrance:a.vibrance/100,u_saturation:a.saturation/100,u_clarity:a.clarity/100,u_vignette:a.vignette/100};for(const[name,value]of Object.entries(uniforms))gl.uniform1f(gl.getUniformLocation(program,name),value);gl.viewport(0,0,width,height);gl.drawArrays(gl.TRIANGLES,0,6);return true;}
function renderFallback(canvas:HTMLCanvasElement,image:HTMLImageElement,width:number,height:number,a:Adjustments){canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Canvas không khả dụng.');ctx.filter=`brightness(${Math.pow(2,a.exposure)*100}%) contrast(${100+a.contrast}%) saturate(${100+a.saturation+a.vibrance*.5}%)`;ctx.drawImage(image,0,0,width,height);ctx.filter='none';}
function renderVariant(image:HTMLImageElement,width:number,height:number,a:Adjustments){const canvas=document.createElement('canvas');try{if(!renderWebGL(canvas,image,width,height,a))renderFallback(canvas,image,width,height,a);}catch{renderFallback(canvas,image,width,height,a);}return canvas;}
function combined(global:Adjustments,local:Adjustments):Adjustments{return Object.fromEntries(Object.keys(global).map(key=>[key,global[key as keyof Adjustments]+local[key as keyof Adjustments]])) as Adjustments;}

export function createMaskCanvas(mask:MaskDefinition,width:number,height:number){const hard=document.createElement('canvas');hard.width=width;hard.height=height;const ctx=hard.getContext('2d');if(!ctx)return hard;ctx.fillStyle='white';ctx.strokeStyle='white';ctx.lineCap='round';ctx.lineJoin='round';const g=mask.geometry;
  if(mask.type==='brush'){const strokes=g.strokes||[g.points||[]];const size=(g.brushSize||.08)*Math.min(width,height);for(const points of strokes){if(points.length===1){ctx.beginPath();ctx.arc(points[0].x*width,points[0].y*height,size/2,0,Math.PI*2);ctx.fill();}else if(points.length>1){ctx.lineWidth=size;ctx.beginPath();ctx.moveTo(points[0].x*width,points[0].y*height);for(const point of points.slice(1))ctx.lineTo(point.x*width,point.y*height);ctx.stroke();}}}
  if(mask.type==='radial'){const center=g.center||{x:.5,y:.5},rx=(g.radiusX||.3)*width,ry=(g.radiusY||.3)*height;ctx.save();ctx.translate(center.x*width,center.y*height);ctx.scale(1,ry/rx);const gradient=ctx.createRadialGradient(0,0,rx*(1-mask.feather),0,0,rx);gradient.addColorStop(0,'white');gradient.addColorStop(1,'transparent');ctx.fillStyle=gradient;ctx.beginPath();ctx.arc(0,0,rx,0,Math.PI*2);ctx.fill();ctx.restore();}
  if(mask.type==='linear'){const start=g.start||{x:.5,y:.2},end=g.end||{x:.5,y:.8};const gradient=ctx.createLinearGradient(start.x*width,start.y*height,end.x*width,end.y*height);const edge=Math.max(0,Math.min(.95,mask.feather));gradient.addColorStop(0,'transparent');gradient.addColorStop(Math.max(.01,1-edge),'white');gradient.addColorStop(1,'white');ctx.fillStyle=gradient;ctx.fillRect(0,0,width,height);}
  let result=hard;if(mask.type==='brush'&&mask.feather>0){result=document.createElement('canvas');result.width=width;result.height=height;const blur=result.getContext('2d');if(blur){blur.filter=`blur(${mask.feather*Math.min(width,height)*.08}px)`;blur.drawImage(hard,0,0);blur.filter='none';}}
  if(mask.inverted){const inverted=document.createElement('canvas');inverted.width=width;inverted.height=height;const inverse=inverted.getContext('2d');if(inverse){inverse.fillStyle='white';inverse.fillRect(0,0,width,height);inverse.globalCompositeOperation='destination-out';inverse.drawImage(result,0,0);result=inverted;}}
  if(mask.opacity<1){const faded=document.createElement('canvas');faded.width=width;faded.height=height;const fade=faded.getContext('2d');if(fade){fade.globalAlpha=mask.opacity;fade.drawImage(result,0,0);result=faded;}}
  return result;
}

export function renderImage(canvas:HTMLCanvasElement,image:HTMLImageElement,editorDocument:EditorDocument,maxDimension=1800){const scale=Math.min(1,maxDimension/Math.max(image.naturalWidth,image.naturalHeight)),width=Math.max(1,Math.round(image.naturalWidth*scale)),height=Math.max(1,Math.round(image.naturalHeight*scale));canvas.width=width;canvas.height=height;const output=canvas.getContext('2d');if(!output)throw new Error('Canvas không khả dụng.');output.clearRect(0,0,width,height);output.drawImage(renderVariant(image,width,height,editorDocument.adjustments),0,0);for(const mask of editorDocument.masks){if(!mask.enabled)continue;const local=renderVariant(image,width,height,combined(editorDocument.adjustments,mask.adjustments));const layer=document.createElement('canvas');layer.width=width;layer.height=height;const layerContext=layer.getContext('2d');if(!layerContext)continue;layerContext.drawImage(local,0,0);layerContext.globalCompositeOperation='destination-in';layerContext.drawImage(createMaskCanvas(mask,width,height),0,0);output.drawImage(layer,0,0);}}
export function drawMaskOverlay(canvas:HTMLCanvasElement,mask:MaskDefinition|null,width:number,height:number){canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d');if(!ctx)return;ctx.clearRect(0,0,width,height);if(!mask)return;ctx.globalAlpha=.5;ctx.drawImage(createMaskCanvas(mask,width,height),0,0);ctx.globalCompositeOperation='source-in';ctx.fillStyle='#ff3568';ctx.fillRect(0,0,width,height);}
export async function exportRenderedImage(image:HTMLImageElement,editorDocument:EditorDocument,type:'image/jpeg'|'image/png'|'image/webp'='image/jpeg',quality=.92){const canvas=document.createElement('canvas');renderImage(canvas,image,editorDocument,Math.max(image.naturalWidth,image.naturalHeight));return new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('Không thể xuất ảnh.')),type,quality));}
